#pragma once

#define GRAPHICS_PIXMAP_ITEM 0
#define GRAPHICS_TEXT_ITEM 1
#define GRAPHICS_PIXMAP_BACKGROUND_ITEM 2
#define GRAPHICS_PIXMAP_LIGHT_ITEM 3
#define GRAPHICS_PIXMAP_MULTIPLE_LIGHT_ITEM 4
#define GRAPHICS_PIXMAP_IBRE_ITEM 5
#define GRAPHICS_PIXMAP_BUTTON_INPUT_ITEM 6
#define GRAPHICS_BAR_ITEM 7
#define GRAPHICS_RECT_ITEM 8
#define GRAPHICS_SLIDER_ITEM 9
#define INNER_DASHBOARD_ITEM 10
#define INNER_WIDGET_ITEM 11

